# Generate the following six parameters with:
# ./psono/manage.py fileserver fsgenerateserverkeys CLUSTER_ID

SECRET_KEY: 'SOME SUPER SECRET KEY THAT SHOULD BE RANDOM AND 32 OR MORE DIGITS LONG'
PRIVATE_KEY: '5f02021c4c0e83c99b007ccb595172c3a9bc204568c12c0b53a820968430d3cc'
PUBLIC_KEY: '76bea610db1dc6d4cae3f90fbb98383e3c9dfc01a0a0dd59cadf3dc3a3c5e00a'
SERVER_URL: 'https://example.com/server'
SERVER_PUBLIC_KEY: '02da2ad857321d701d754a7e60d0a147cdbc400ff4465e1f57bc2d9fbfeddf0b'
CLUSTER_ID: 'aae7f116-506d-4e17-bf53-f62868a218d6'
CLUSTER_PRIVATE_KEY: 'b571a54c5c2b80b3bd31ae7934f7457b719f7ea11f1782b41ed84d1a7d6656f8'
SHARDS: []


# Switch DEBUG to false if you go into production
DEBUG: True

# Adjust this according to Django Documentation https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts
ALLOWED_HOSTS: ['*']

# Should be the URL of the host under which the server is reachable
# If you open the url you should have a text similar to {"detail":"Authentication credentials were not provided."}
HOST_URL: 'https://example.com/fileserver01'


# Cache enabled without belows Redis may lead to unexpected behaviour
CACHE_ENABLE: False

# Cache with Redis
# By deault you should use something different than database 0 or 1, e.g. 13 (default max is 16, can be configured in
# redis.conf) possible URLS are:
#    redis://[:password]@localhost:6379/0
#    rediss://[:password]@localhost:6379/0
#    unix://[:password]@/path/to/socket.sock?db=0
CACHE_REDIS: False
CACHE_REDIS_LOCATION: 'redis://127.0.0.1:6379/13'

# Disables Throttling (necessary for unittests to pass) by overriding the cache with a dummy cache
# https://docs.djangoproject.com/en/2.0/topics/cache/#dummy-caching-for-development
THROTTLING: False

